### ISSUE TITLE
Invalid username or password on first login

### ISSUE THREAD

**Issue by PrzemekSkw** [getferdi/server#115]
Hello, I want to try Ferdi with docker-compose but cannot login in local address: http://192.168.0.111:3333.

I set in docker compose:
```
version: "2"
services:
  ferdi-server:
    image: getferdi/ferdi-server
    container_name: ferdi-server
    environment:
      - NODE_ENV=development
      - APP_URL=localhost
      - DB_CONNECTION=sqlite
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=ferdi
      - DB_SSL=false
      - MAIL_CONNECTION=smtp
      - SMTP_HOST=hs14.linux.pl
      - SMTP_PORT=465
      - MAIL_SSL=true
      - MAIL_USERNAME=zakupy@.......
      - MAIL_PASSWORD=w..........
      - MAIL_SENDER=hs10.linux.pl
      - IS_CREATION_ENABLED=true
      - IS_DASHBOARD_ENABLED=true
      - IS_REGISTRATION_ENABLED=true
      - CONNECT_WITH_FRANZ=false
      - DATA_DIR=/data
      - PUID=1000
      - PGID=1000
    volumes:
      - ferdi-database-vol:/data
      - ferdi-recipes-vol:/app/recipes
    ports:
      - 3333:3333
    restart: unless-stopped
volumes:
  ferdi-database-vol:
  ferdi-recipes-vol:
```

Regards.
